- name: Database Server Setup
  hosts: db
  become: true
  tasks:
    - name: Install MongoDB
      yum:
        name: mongodb-org
        state: present

    - name: Start and Enable MongoDB Service
      service:
        name: mongod
        state: started
        enabled: true

    - name: Secure MongoDB Instance
      copy:
        dest: /etc/mongod.conf
        content: |
          net:
            bindIp: 127.0.0.1,{{ ansible_default_ipv4.address }}
          security:
            authorization: enabled

    - name: Restart MongoDB for Configuration Changes
      service:
        name: mongod
        state: restarted

    - name: Create MongoDB User and Database
      command: >
        mongo admin --eval "db.createUser({user: 'lucky', pwd: 'lucky_123', roles: [{role: 'readWrite', db: 'mernApp'}]})"
